FROM confluentinc/cp-kafka-connect:5.3.2

RUN confluent-hub install confluentinc/kafka-connect-sftp:2.1.1 --no-prompt
RUN confluent-hub install confluentinc/kafka-connect-s3-source:1.3.2 --no-prompt


